#!/usr/bin/env bash

set -euo pipefail

HERE="$(dirname "$(realpath "${BASH_SOURCE[0]}")")"
cd "$HERE/.."

cargo build
cargo objcopy --bin 'ghanima' -- \
    -O binary "target/thumbv6m-none-eabi/debug/ghanima"

cd "$HERE/../remote"
arm-none-eabi-gdb "../target/thumbv6m-none-eabi/debug/ghanima" -x ./gdbinit
